const FETCH_PUBLIC_PRODUCTS_REQUEST = "FETCH_PUBLIC_PRODUCTS_REQUEST";
const FETCH_PUBLIC_PRODUCTS_SUCCESS = "FETCH_PUBLIC_PRODUCTS_SUCCESS";
const FETCH_PUBLIC_PRODUCTS_FAILURE = "FETCH_PUBLIC_PRODUCTS_FAILURE";
const FETCH_MY_PRODUCTS_REQUEST = "FETCH_MY_PRODUCTS_REQUEST";
const FETCH_MY_PRODUCTS_SUCCESS = "FETCH_MY_PRODUCTS_SUCCESS";
const FETCH_MY_PRODUCTS_FAILURE = "FETCH_MY_PRODUCTS_FAILURE";

export {
  FETCH_PUBLIC_PRODUCTS_REQUEST,
  FETCH_PUBLIC_PRODUCTS_SUCCESS,
  FETCH_PUBLIC_PRODUCTS_FAILURE,
  FETCH_MY_PRODUCTS_REQUEST,
  FETCH_MY_PRODUCTS_SUCCESS,
  FETCH_MY_PRODUCTS_FAILURE,
};
