# Generated by Django 3.1.2 on 2020-11-05 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Computers and Accessories', 'Computers And Accessories'), ('Phones and Gadgets', 'Phones And Gadgets'), ('Electronics', 'Electronics'), ('Clothing and Fashion', 'Clothing And Fashion'), ('Home and Kitchen', 'Home And Kitchen'), ('Kids and Toys', 'Kids And Toys'), ('Others', 'Others')], default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
