const FETCH_MY_PRODUCTS_REQUEST = "FETCH_MY_PRODUCTS_REQUEST";
const FETCH_MY_PRODUCTS_SUCCESS = "FETCH_MY_PRODUCTS_SUCCESS";
const FETCH_MY_PRODUCTS_FAILURE = "FETCH_MY_PRODUCTS_FAILURE";

const LIST_PRODUCT_REQUEST = "LIST_PRODUCT_REQUEST";
const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
const LIST_PRODUCT_FAILURE = "LIST_PRODUCT_FAILURE";

export {
  FETCH_MY_PRODUCTS_REQUEST,
  FETCH_MY_PRODUCTS_SUCCESS,
  FETCH_MY_PRODUCTS_FAILURE,
  LIST_PRODUCT_REQUEST,
  LIST_PRODUCT_SUCCESS,
  LIST_PRODUCT_FAILURE,
};
